name: WebGL to Itch (production)

on:
  push:
    branches:
      - main

jobs:
  build:
    name: WebGL Build and Deploy
    runs-on: ubuntu-latest
    steps:
      # Checkout
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          lfs: true

      # Cache
      - uses: actions/cache@v4
        with:
          path: Library
          key: Library-GameOff2024-WebGL
          restore-keys: |
            Library-GameOff2024-
            Library-

      # Notification 1
      - name: Discord Notify Start
        uses: tsickert/discord-webhook@v5.3.0
        with:
          webhook-url: https://discord.com/api/webhooks/1304296004555767892/SBpA_0_rLBRNY5qZ-mzb4gOhAQHjoBvInt3hKoe0Fm2SUbx8nwZPRvVY6pZG-jphFssE
          content: ":wrench: **New build started** WebGL build started on `develop` branch for the game-off-2024 project. This will take time. CPP doesn't transpile to WASM quickly.."
      
      # Build
      - name: Unity WebGL Build
        uses: game-ci/unity-builder@v4
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          targetPlatform: WebGL

      # Output
      - uses: actions/upload-artifact@v4
        with:
          name: Build
          path: build
          
      - name: Butler Push to Itch.io (production)
        uses: manleydev/butler-publish-itchio-action@master
        env:
          BUTLER_CREDENTIALS: ${{ secrets.BUTLER_CREDENTIALS }}
          CHANNEL: webgl
          ITCH_GAME: game-off-2024
          ITCH_USER: citizendevelopers
          PACKAGE: build

      # Notification 2
      - name: Discord Notify Complete
        uses: tsickert/discord-webhook@v5.3.0
        with:
          webhook-url: https://discord.com/api/webhooks/1304296004555767892/SBpA_0_rLBRNY5qZ-mzb4gOhAQHjoBvInt3hKoe0Fm2SUbx8nwZPRvVY6pZG-jphFssE
          content: ":white_check_mark: **WebGL build complete** a new build is available at https://citizendevelopers.itch.io/game-off-2024"